{
    'name': '文件管理',
    'version': '1.0',
    'summary': '管理文件、图纸和合同',
    'description': '一个综合文件管理系统，用于管理、存储和跟踪各类文档、技术图纸和合同',
    'author': '您的名字',
    'website': '您的网站',
    'category': 'Document Management',
    'depends': [
        'base',
        'mail',
        'project',
        'product',
        'sale_management',
        'documents',
        'crm',  
        'hr_expense',
        'purchase',
    ],
    'data': [
        'security/document_security.xml',
        'security/ir.model.access.csv',
        'views/document_views.xml',
        'views/drawing_views.xml',
        'views/contract_views.xml',
        'views/product_views.xml',
        'views/project_views.xml',
        'views/document_menu.xml',
        'views/sale_views.xml',
        'views/crm_lead_views.xml',
        'views/hr_expense_views.xml',
        'views/purchase_order_views.xml',

    ],
    'application': True,
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}